# Generated by Django 3.0.3 on 2020-02-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('contact_count', models.IntegerField(blank=True)),
                ('second_infection', models.IntegerField(blank=True, null=True)),
                ('lat', models.IntegerField(blank=True)),
                ('lng', models.IntegerField(blank=True)),
                ('index', models.IntegerField()),
                ('log_type', models.CharField(max_length=10)),
            ],
        ),
    ]
