# Generated by Django 3.0.3 on 2020-02-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeds',
            new_name='Feed',
        ),
    ]
