# Generated by Django 3.0.3 on 2020-02-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20200207_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
