# Generated by Django 3.0.3 on 2020-02-06 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200206_1206'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='patients.Patient'),
        ),
    ]
