# Generated by Django 3.0.3 on 2020-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient_count', models.IntegerField()),
                ('cure_count', models.IntegerField()),
                ('death_count', models.IntegerField()),
            ],
        ),
    ]
