# Generated by Django 3.0.3 on 2020-02-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lng',
        ),
    ]
