# Generated by Django 3.0.3 on 2020-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200209_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='infected_route',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
