# Generated by Django 3.0.3 on 2020-02-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20200206_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_count',
            field=models.IntegerField(default=0),
        ),
    ]
