# Generated by Django 3.0.3 on 2020-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200207_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
