# Generated by Django 3.0.3 on 2020-02-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200220_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('increase', models.IntegerField()),
            ],
        ),
    ]
