# Generated by Django 3.0.3 on 2020-02-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLocationFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('increase', models.IntegerField()),
            ],
        ),
    ]
